

DROP TABLESPACE TRANSACCIONAL INCLUDING CONTENTS AND DATAFILES;
CREATE TABLESPACE TRANSACCIONAL DATAFILE 'TRANSACCIONALFILE.DBF' SIZE 5M;
DROP TABLESPACE DIMENSIONAL INCLUDING CONTENTS AND DATAFILES;
CREATE TABLESPACE DIMENSIONAL DATAFILE 'DIMESIONALFILE.DBF' SIZE 5M;


DROP USER TRANSACCION CASCADE;
CREATE USER TRANSACCION IDENTIFIED BY TRANS123456
DEFAULT TABLESPACE TRANSACCIONAL
QUOTA UNLIMITED ON TRANSACCIONAL;

DROP USER DIMENSION CASCADE;
CREATE USER DIMENSION IDENTIFIED BY DIME123456
DEFAULT TABLESPACE DIMENSIONAL
QUOTA UNLIMITED ON DIMENSIONAL;


GRANT CONNECT, CREATE SESSION, CREATE VIEW, CREATE TABLE, ALTER SESSION, CREATE SEQUENCE, RESOURCE TO TRANSACCION, DIMENSION;

GRANT SELECT ANY TABLE TO DIMENSION;