

DROP TABLESPACE TRANSPORTE INCLUDING CONTENTS AND DATAFILES;
CREATE TABLESPACE TRANSPORTE DATAFILE 'transporte.DBF' SIZE 5M;


DROP USER AGENTES CASCADE;
CREATE USER AGENTES IDENTIFIED BY 123456
DEFAULT TABLESPACE TRANSPORTE
QUOTA UNLIMITED ON TRANSPORTE;


GRANT CONNECT, CREATE SESSION, CREATE VIEW, CREATE TABLE, ALTER SESSION, CREATE SEQUENCE, RESOURCE TO AGENTES;

GRANT SELECT ANY TABLE TO AGENTES;